FROM balenalib/%%RESIN_MACHINE_NAME%%-ubuntu:bionic-build
MAINTAINER Moritz Ulmer <moritz.ulmer@posteo.de>

# Install the DHCP server
RUN apt-get update && apt-get install -y \
    dnsmasq \
&& rm -rf /var/lib/apt/lists/*

# Copy the start script and dnsmasq server configuration
COPY start.sh /usr/local/bin/
COPY dnsmasq.conf /etc/dnsmasq.conf

ENTRYPOINT ["bash", "start.sh"]

