FROM resin/%%RESIN_MACHINE_NAME%%-debian:jessie

WORKDIR /usr/src/app/
ENV INITSYSTEM on

# python-dbus for dbus communication
RUN apt-get update && apt-get install -yq \
    python-dbus

COPY *.py ./
COPY avahi avahi
COPY start.sh ./

CMD ["bash", "start.sh"]
