FROM balenalib/%%RESIN_MACHINE_NAME%%-ubuntu-python:3.7-bionic-build

WORKDIR /usr/src/app/
ENV INITSYSTEM on

# Allow communication to the host avahi daemon
ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

COPY *.py ./
COPY avahi avahi
COPY start.sh ./

CMD ["bash", "start.sh"]
