FROM balenalib/%%RESIN_MACHINE_NAME%%-ubuntu-python:3.7-bionic-build

WORKDIR /usr/src/app/
ENV INITSYSTEM on

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY *.py ./
COPY start.sh ./

CMD ["bash", "start.sh"]
