FROM balenalib/%%RESIN_MACHINE_NAME%%-ubuntu:bionic-build
MAINTAINER Moritz Ulmer <moritz.ulmer@posteo.de>

RUN apt-get update && apt-get install -y \
    mosquitto \
    mosquitto-clients \
&& rm -rf /var/lib/apt/lists/*

COPY start.sh ./
COPY mosquitto.conf /mqtt/config/mosquitto.conf
VOLUME ["/mqtt/config", "/mqtt/data", "/mqtt/log"]

EXPOSE 1883 9001
CMD ["/usr/sbin/mosquitto", "-c", "/mqtt/config/mosquitto.conf"]
